seed: 19260817
train_ratio: 0.9
normalize_mean:
  - 0.5
  - 0.5
  - 0.5
normalize_std:
  - 0.5
  - 0.5
  - 0.5
random_resize_bound: 0.25
random_erasing_p: 0.25
mixup_alpha: 0.8
cutmix_alpha: 1
label_smoothing: 0.1
num_repeated_aug: 3
drop_path_rate: 0.1
optimizer: adamw
lr: 0.001
weight_decay: 0.001
num_epochs: 200
train_batch_size: 384
test_batch_size: 768
num_samples: 8
perturbation_interval: 10
